stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  script:
    - docker build -t 10.3.1.10:5000/microblog:latest .
    - docker push 10.3.1.10:5000/microblog:latest
  tags:
    - docker

deploy_to_swarm:
  stage: deploy
  image: docker:20.10.16
  script:
    - docker stack deploy -c docker-compose.yml microblog-stack
  tags:
    - docker
