stages:
  - build


build:
  stage: build
  tags:
    - docker
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  script:
    - echo $DOCKER_HOST
    - docker info
    - docker build -t 192.168.1.10:5000/microblog:latest .
    - docker push 192.168.1.10:5000/microblog:latest
