stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  script:
    - docker build -t 10.3.1.10:5050/microblog:latest .
    - docker build -f Dockerfile-nginx -t 10.3.1.10:5050/nginx:latest .
    - docker build -f Dockerfile-prometheus -t 10.3.1.10:5050/prometheus:latest .
    - docker push 10.3.1.10:5050/microblog:latest
    - docker push 10.3.1.10:5050/nginx:latest
    - docker push 10.3.1.10:5050/prometheus:latest
  tags:
    - docker
  only:
    - cluster-stack

deploy_to_swarm:
  stage: deploy
  image: docker:20.10.16
  script:
    - docker stack deploy -c docker-compose.yml microblog-stack
  tags:
    - docker
  only:
    - cluster-stack
