version: '3.8'

services:
  microblog:
    image: ${REGISTRY_URL}/microblog:latest
    environment:
      - DATABASE_URL=postgresql://postgres:microblog@postgres:5432/microblog
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - LOG_TO_STDOUT=${LOG_TO_STDOUT}
    ports:
      - "5000:5000"
      - "9100:9100"
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - microblog-net
    depends_on:
      - postgres

  prometheus:
    image: ${REGISTRY_URL}/prometheus:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - microblog-net
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - microblog-net
    volumes:
      - grafana-data:/var/lib/grafana

  nginx:
    image: ${REGISTRY_URL}/nginx:latest
    ports:
      - "443:443"
      - "9090:9090"
      - "3000:3000"
    environment:
      - MANAGER_IP=${MANAGER_IP}
    depends_on:
      - microblog
      - prometheus
      - grafana
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - microblog-net

  registry:
    image: registry:2
    ports:
      - "5001:5000"
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
    volumes:
      - registry-data:/var/lib/registry
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - microblog-net
    # Only start registry if ENABLE_REGISTRY is true
    condition: ${ENABLE_REGISTRY:-true} == true ? service_started :service_completed_successfully

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=microblog
      - POSTGRES_DB=microblog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    networks:
      - microblog-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:microblog@postgres:5432/microblog?sslmode=disable
    networks:
      - microblog-net
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  microblog-net:
    driver: overlay

volumes:
  grafana-data:
  prometheus-data:
  registry-data:
  postgres-data:
