version: '3.8'

services:
  microblog:
    image: 10.3.1.10:5000/microblog:latest
    ports:
      - "5000:5000"   
    deploy:
      mode: replicated
      replicas: 3 
      placement:
        constraints:
          - node.role != manager
      update_config:
        paralellelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - microblog-net

networks:
  microblog-net:
    driver: overlay
