global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microblog'
    static_configs:
      - targets: ['microblog:5000']
    metrics_path: /metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
